### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dereuromark** [gwhitcher/CakeBlog#2]
Nice work so far!

Here a little bit of feedback:
- dont version control vendor stuff, let composer install it, but do not commit those files
- use Migrations plugin for your Init migration instead of an sql file. You can still read it from file, but this way it is just a simple command: "cake Migrations migrate" :) See https://github.com/dereuromark/cakephp-sandbox/blob/3.0/config/Migrations/20150117000256_init.php From there on it is also super-easy to publish DB structure changes this way.
- remove cakephp/plugin-installer dependency, not needed anymore
- provide some basic test coverage and assert it using travis

Once all these points are done, feel free to add your blog (incl. a linked demo blog maybe from your readme) to https://github.com/FriendsOfCake/awesome-cakephp#web-applications

**Comment by gwhitcher** [comment]
Wow thanks man.  I've used some of the tutorials in your blog for some of my projects.  I would love the opportunity to do this.  I will let you know when these are completed.

**Comment by gwhitcher** [comment]
Hey dereuromark,
I went ahead and did the requested changes.  Just didn't do travis testing as I was confused on the database implementation in 3.0.  Your tutorial on your site only is for 2.6.  I test it myself though through personal use so I know it's good to go.  I did go ahead and add CakeBlog to the list.  Thanks!  Feel free to contact me with any questions http://georgewhitcher.com/contact
