### ISSUE TITLE
cannot install using composer on cakephp 3.1.5

### ISSUE THREAD

**Issue by zamaliphe** [gwhitcher/CakeBlog#3]
composer require cakeblog/cakeblog:dev-master

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update

                                                                                                                             
  [Composer\DependencyResolver\SolverProblemsException]                                                                      
    Problem 1                                                                                                                
      - The requested package cakeblog/cakeblog could not be found in any version, there may be a typo in the package name.  
  Potential causes:                                                                                                          
   - A typo in the package name                                                                                              
   - The package is not available in a stable-enough version according to your minimum-stability setting                     
     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.                           
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.                                
                                                             

==============================================

composer require cakeblog/cakeblog:~2.5.9
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakeblog/cakeblog 2.5.9 requires cakeblog/cakeblog dev-master -> satisfiable by cakeblog/cakeblog[dev-master].
    - Can only install one of: cakeblog/cakeblog[dev-master, 2.5.9].
    - Installation request for cakeblog/cakeblog ~2.5.9 -> satisfiable by cakeblog/cakeblog[2.5.9].

**Comment by gwhitcher** [comment]
At this time I am unsure as to what the issue is.  It is an issue with composer which I am kind of new to.  You can temporarily install it with the follow:
git clone https://github.com/gwhitcher/cakeblog.git

**Comment by zamaliphe** [comment]
i thing the problim is a requirement loop 
IE you require ( package A )
package A require ( package B )
package B require ( package A )

**Comment by gwhitcher** [comment]
Hello Zamaliphe,
Thank you for your input on this issue.  I believe I have resolved it.  I think it was a number of issues that were due to composer and my composer.json.
